mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('^admin/', admin.site.urls),
    url('^transit/', include('transit.urls', namespace= 'transit')),
]

transit/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url('^$', views.home, name='home'),
    url('^admin/', admin.site.urls),
    url('^lineConnections/', views.findConnections, name='findConnections'),
    url(r'^(?P<pk>[0-9]+)/$', views.StationDetails.as_view(), name="stationDetails")
]

transit/models.py
from django.db import models

LINE_COLORS = (
    ('GR', 'Green'),
    ('BL', 'Blue'),
    ('SV', 'Silver'),
    ('RD', 'Red'),
    ('OR', 'Orange'),
    ('YL', 'Yellow')
)

class Line(models.Model):
    name = models.CharField(max_length=2, unique=True, choices=LINE_COLORS)
    color = models.CharField(max_length=6, null=True)
    start_station = models.CharField
    end_station = models.CharField

    def __str__(self):
        return self.color

class Station(models.Model):
    name = models.CharField(max_length=40, null=True)
    street = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=30, null=True)
    state = models.CharField(max_length=2, null=True)
    zip = models.IntegerField(null=True)
    code = models.CharField(max_length=3, unique=True, null=True)
    line = models.ForeignKey(Line, on_delete=models.CASCADE, related_name='primary_line')
    longitude = models.DecimalField(decimal_places=6, max_digits=9, null=True)
    latitude = models.DecimalField(decimal_places=6, max_digits=9, null=True)
    line2 = models.ForeignKey(Line, on_delete=models.CASCADE, null=True, blank=True, related_name='secondary_line')
    line3 = models.ForeignKey(Line, on_delete=models.CASCADE, null=True, blank=True, related_name='tertiary_line')
    code2 = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.code

transit/forms.py
from .models import Line, LINE_COLORS
from django import forms

class LineForm(forms.ModelForm):
    class Meta:
        model = Line
        fields = {'name'}

class LineChoices(forms.Form):
    line1 = forms.ModelChoiceField(
        queryset=Line.objects.all(),
        empty_label='Select beginning line',
        to_field_name='name',
    )
    #line2 = forms.ModelChoiceField(
    #    queryset=Line.objects.all(),
    #    empty_label='Select destination line',
    #    to_field_name='color',
    #)

transit/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from . import allstations, getmetro, lines
from .models import Line, Station
from django.template.context_processors import csrf
from django.template.context import RequestContext
from django.views.generic.detail import DetailView
from .forms import LineForm, LineChoices
from django.db.models import Q

def home(request):
    return render(request, 'transit/home.html')

def findConnections(request):
    if request.GET.items():
        form = LineChoices(request.GET)
        if form.is_valid():
            current_line_dict = request.GET
            for i in current_line_dict.values():
                current_line = i
            args = { }
            args['form'] = form
            current_line_object = Line.objects.filter(name=current_line)
            station_list = Station.objects.select_related('line').filter(Q(line_id=current_line_object) | Q(line2_id=current_line_object) | Q(line3_id=current_line_object))
            args['station_list'] = station_list
            return render(request, 'transit/lineConnections.html', args)
    form = LineChoices()
    args = { }
    args['form'] = form
    return render(request, 'transit/lineConnections.html', args)

class StationDetails(DetailView):
    model = Station
    name = 'stationDetails'

transit/templates/transit/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WMATA Transit Guide</title>
</head>
<section>
    <h1>WMATA Guide</h1>
    <p><a href="{% url 'transit:findConnections' %}">Find available stations at the different lines.</a></p>
</section>

transit/templates/transit/lineConnections.html
<section>
    <form action="" method="get">
        {% for field in form %}
            {{ field }}
        {% endfor %}
    <input type="submit" value="Get station list" />
    </form>
    <p>See below list of stations: </p>
    <!-- Need to account for stations that have multiple lines -->
    <ul>
        {% for station in station_list %}
            <li><a href="{% url 'transit:stationDetails' station.id %}">{{ station.name }}</a></li>
        {% endfor %}
    </ul>
</section>
<section>
    <p><a href="{% url 'transit:home' %}">Home</a></p>
</section>

transit/templates/transit/station_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ station.name }}</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body {
        height: 50%;
        margin: 0;
        padding: 0;
      }
        test1 {
        color="red";
      }
        #test3 {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 50%;
        width: 50%;
      }
    </style>
</head>
<section id="test1">
<p>Station Lines:</p>
<ul>
    <li>{{ station.line }}</li>
    {% if station.line2 is not None %}
    <li>{{ station.line2 }}</li>
    {% endif %}
    {% if station.line3 is not None %}
    <li>{{ station.line3 }}</li>
    {% endif %}
    {% if station.line4 is not None %}
    <li>{{ station.line4 }}</li>
    {% endif %}
    {% if station.code2.line is not None %}
    <li>{{ station.code2.line }}</li>
    {% endif %}
</ul>
</section>
<section id="test2">
    <p><a href="{% url 'transit:home' %}">Home</a></p>
</section>
<body>
    <div id="map"></div>
    <script>
      var map;
      var infowindow;

      function initMap() {
        var pyrmont = {lat: {{ station.latitude }}, lng: {{ station.longitude }} };

        map = new google.maps.Map(document.getElementById('map'), {
          center: pyrmont,
          zoom: 17
        });
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBAdwx0aVnGoIhuadkQC2x0ANEP_vJBr-U&libraries=places&callback=initMap" async defer></script>
</body>
</html>

transit/templates/transit/stationdetails.html
<section>
<p>{{ this_station.Name }}</p>
</section>
<section>
<p>test</p>

</section>